### ISSUE TITLE
Add Discord Link and Participant Package

### ISSUE THREAD

**Issue by grahamhoyes** [ieeeuoft/makeuoft-site-2021#22]
Once logistics gives us the links, set them in the settings files so they appear as necessary

**Comment by grahamhoyes** [comment]
Discord link: https://discord.gg/UZ4bD3vp

**Comment by lisa-sa-li** [comment]
Participant Package: https://docs.google.com/document/d/1P-Q1xqVl-C2c2OMaco45TdjPFtYe0pOhIzmGs1GaPoc/edit?usp=sharing
